import test from 'node:test';
import assert from 'node:assert/strict';
import { Scene, Vector3 } from 'three';
import { Match } from '../src/match.js';
import { PerspectiveCamera } from 'three';
import { GameCamera } from '../src/game-camera.js';

// No renderer needed: these integration tests run the real scene transforms,
// animated boots, input consumption and match simulation without a GPU.
const ctx=new Proxy({}, {get:()=>()=>{},set:()=>true});
globalThis.document={createElement:()=>({getContext:()=>ctx,remove(){},className:'',textContent:''}),querySelector:()=>({append(){}})};
function fixture(){const input={clear(){this.release=null;},update(){},take(){return false;},direction(){return {x:0,z:0};},curve:0,sprint:false,release:null};const m=new Match(new Scene(),input,{burst(){}},{tone(){}});m.setup(0,true,180);m.running=true;return {m,input};}
test('la bota animada puede conectar un tiro real cercano',()=>{const {m,input}=fixture();m.active.position.set(-.6,0,0);m.active.animate(0);input.release={type:'shot',time:.7};for(let i=0;i<28;i++)m.step(1/120);assert.ok(m.ball.velocity.x>10,`Velocidad de tiro insuficiente: ${m.ball.velocity.x}`);assert.ok(m.ball.velocity.y>0);});
test('soltar un tiro lejos del balón no lo mueve por magia',()=>{const {m,input}=fixture();m.active.position.set(-10,0,0);input.release={type:'shot',time:1};for(let i=0;i<30;i++)m.step(1/120);assert.ok(m.ball.position.length()<.3);});
test('el marcador cuenta un solo gol y reinicia el saque',()=>{const {m}=fixture();m.ball.position.set(30.1,1,0);m.ball.velocity.set(30,0,0);m.step(1/120);assert.deepEqual(m.score,[1,0]);for(let i=0;i<300;i++)m.step(1/120);assert.deepEqual(m.score,[1,0]);assert.ok(Math.abs(m.ball.position.x)<1);});
test('pausar detiene el cronómetro y la física',()=>{const {m}=fixture();m.running=false;m.ball.velocity.set(10,0,0);m.step(1);assert.equal(m.elapsed,0);assert.equal(m.ball.position.x,0);});
test('el descanso ocurre una vez y el partido termina a los 90 escalados',()=>{const {m}=fixture();m.practice=false;let halves=0,ended=0;m.onHalf=()=>halves++;m.onEnd=()=>ended++;m.elapsed=89.999;m.step(.01);assert.equal(halves,1);m.step(.01);assert.equal(halves,1);m.elapsed=179.999;m.step(.01);assert.equal(ended,1);assert.equal(m.running,false);});
test('cambiar de jugador elige un compañero de campo',()=>{const {m}=fixture();const old=m.active;m.switchPlayer();assert.notEqual(m.active,old);assert.equal(m.active.team,0);assert.equal(m.active.keeper,false);});
test('la tecla de cambio cambia al jugador activo durante el partido',()=>{const {m,input}=fixture();const old=m.active;input.take=action=>action==='switchPlayer';m.step(1/120);assert.notEqual(m.active,old);assert.equal(m.active.team,0);});
test('un saque de banda no cambia de jugador sin que se pulse cambio',()=>{const {m}=fixture();const old=m.active;m.ball.lastTouch=1;m.ball.position.set(0,.22,19);m.restartFromOut();assert.equal(m.active,old);});

test('conducción cercana conserva el balón al correr, girar y frenar',()=>{const {m,input}=fixture();input.direction=()=>({x:1,z:0});for(let i=0;i<180;i++)m.step(1/120);assert.equal(m.control.owner,m.active);assert.ok(m.active.position.distanceTo(m.ball.position)<1.05);input.direction=()=>({x:0,z:-1});for(let i=0;i<90;i++)m.step(1/120);assert.equal(m.control.owner,m.active);assert.ok(m.active.position.distanceTo(m.ball.position)<1.05);input.direction=()=>({x:0,z:0});for(let i=0;i<90;i++)m.step(1/120);assert.ok(m.ball.velocity.length()<.15);assert.ok(m.active.position.distanceTo(m.ball.position)<.9);});
test('la aceleración y el giro están limitados, incluso al invertir la marcha',()=>{const {m}=fixture(),p=m.active;p.move(new Vector3(1,0,0),true,1/120);assert.ok(p.velocity.length()<.2);for(let i=0;i<100;i++)p.move(new Vector3(1,0,0),true,1/120);const before=p.facing.clone();p.move(new Vector3(-1,0,0),true,1/120);assert.ok(before.dot(p.facing)>.99);assert.ok(p.velocity.x>0);for(let i=0;i<180;i++)p.move(new Vector3(-1,0,0),true,1/120);assert.ok(p.velocity.x<0);assert.ok(Number.isFinite(p.facing.x));});
test('un tiro con posesión libera el balón sin volver a pegarlo',()=>{const {m,input}=fixture();for(let i=0;i<15;i++)m.step(1/120);assert.equal(m.control.owner,m.active);input.release={type:'shot',time:.7};for(let i=0;i<40;i++)m.step(1/120);assert.equal(m.control.owner,null);assert.ok(m.ball.velocity.x>10);});
test('sombrerito eleva el balón sobre un rival y permite recuperarlo al caer',()=>{const {m}=fixture();m.step(1/120);assert.ok(m.control.startSkill(m.active,'sombrero'));assert.equal(m.control.owner,null);assert.ok(m.ball.velocity.y>6);let height=0;for(let i=0;i<180;i++){m.step(1/120);height=Math.max(height,m.ball.position.y);}assert.ok(height>2,`Altura: ${height}`);m.active.position.copy(m.ball.position).setY(0).add(new Vector3(-.65,0,0));m.active.velocity.set(0,0,0);m.active.facing.set(1,0,0);m.ball.velocity.set(0,-.1,0);m.ball.position.y=.3;m.control.update(1/120);assert.equal(m.control.owner,m.active);});
test('elástica hace un toque exterior y otro interior sin perder el control',()=>{const {m}=fixture();m.step(1/120);assert.ok(m.control.startSkill(m.active,'elastica'));let min=0,max=0;for(let i=0;i<80;i++){m.step(1/120);const z=m.ball.position.z-m.active.position.z;min=Math.min(min,z);max=Math.max(max,z);}assert.ok(min<-.2,`Exterior: ${min}`);assert.ok(max>.2,`Interior: ${max}`);assert.equal(m.control.owner,m.active);assert.equal(m.control.skill,null);assert.ok(!m.control.startSkill(m.active,'elastica'));});
test('sin posesión no se ejecutan regates',()=>{const {m}=fixture();assert.equal(m.control.startSkill(m.active,'sombrero'),false);assert.equal(m.control.startSkill(m.active,'elastica'),false);assert.equal(m.control.startSkill(m.active,'bicicleta'),false);});
test('la bicicleta mantiene la posesión y da un boost de 2 segundos al terminar',()=>{const {m}=fixture();m.step(1/120);assert.equal(m.control.owner,m.active);assert.ok(m.control.startSkill(m.active,'bicicleta'));assert.equal(m.control.skill.type,'bicicleta');assert.equal(m.active.boost,0);for(let i=0;i<140;i++)m.step(1/120);assert.equal(m.control.skill,null);assert.equal(m.control.owner,m.active);assert.ok(m.active.boost>0,`boost: ${m.active.boost}`);});
function tackleFixture(){const {m}=fixture();m.active.position.set(0,0,0);m.ball.reset(.65,0);m.control.claim(m.active);const rival=m.players.find(p=>p.team===1);rival.position.set(1.45,0,0);rival.facing.set(-1,0,0);rival.startTackle(false);return {m,rival};}
test('una entrada frontal roba el balón y evita la recuperación instantánea',()=>{const {m,rival}=tackleFixture();assert.equal(m.control.tryTackle(rival),true);assert.equal(m.control.owner,rival);assert.ok(m.active.controlLock>0);assert.equal(m.active.hasBall,false);});
test('las entradas no roban a distancia, por detrás del cuerpo ni por el aire',()=>{const {m,rival}=tackleFixture();rival.position.x=3;assert.equal(m.control.tryTackle(rival),false);rival.position.x=-.65;rival.facing.set(1,0,0);assert.equal(m.control.tryTackle(rival),false);rival.position.x=1.4;rival.facing.set(-1,0,0);m.ball.position.y=2;assert.equal(m.control.tryTackle(rival),false);});
test('la elástica puede interrumpirse con una entrada bien colocada',()=>{const {m,rival}=tackleFixture();m.control.startSkill(m.active,'elastica');assert.equal(m.control.tryTackle(rival),true);assert.equal(m.control.skill,null);assert.equal(m.control.owner,rival);});

test('las manos y los codos se articulan al correr y se relajan al parar',()=>{const {m}=fixture(),p=m.active;const before=p.hands[0].getWorldPosition(new Vector3());for(let i=0;i<24;i++){p.move(new Vector3(1,0,0),true,1/120);p.animate(1/120);}assert.ok(p.forearms[0].rotation.x<-.3);assert.ok(Math.abs(p.arms[0].rotation.x)>0.1);assert.ok(before.distanceTo(p.hands[0].getWorldPosition(new Vector3()))>.1);for(let i=0;i<100;i++){p.move(new Vector3(),false,1/120);p.animate(1/120);}assert.ok(Math.abs(p.arms[0].rotation.x)<.01);});
test('la IA ofrece apoyos abiertos y mantiene un solo presionante',()=>{const {m}=fixture();m.setup(0,false,180);m.control.claim(m.active);m.ai.update(.2);const wide=m.players.filter(p=>p.team===0&&(p.index===1||p.index===2));assert.ok(m.ai.plans.get(wide[0]).target.z<-5);assert.ok(m.ai.plans.get(wide[1]).target.z>5);const presser=m.ai.pressers[1];assert.equal(presser.team,1);assert.equal(presser.keeper,false);const defenders=m.players.filter(p=>p.team===1&&!p.keeper&&p!==presser);assert.ok(defenders.every(p=>m.ai.plans.get(p).target.distanceTo(m.ball.position)>3));});
test('la IA reconoce una línea de pase bloqueada',()=>{const {m}=fixture();const from=new Vector3(0,0,0),to=new Vector3(10,0,0);assert.equal(m.ai.laneClearance(from,to,[{position:new Vector3(5,0,0)}]),0);assert.ok(m.ai.laneClearance(from,to,[{position:new Vector3(5,0,4)}])>3);});
test('el portero anticipa la intersección de un tiro',()=>{const {m}=fixture();const keeper=m.players.find(p=>p.team===1);m.ball.position.set(15,.22,0);m.ball.velocity.set(15,0,2);m.ai.update(.2);const target=m.ai.plans.get(keeper).target;assert.ok(target.z>1.5&&target.z<2);});
test('la primera persona sigue los ojos, permite desplazamiento lateral y restaura el cuerpo',()=>{const {m,input}=fixture(),camera=new PerspectiveCamera(),view=new GameCamera(camera,input);view.setMode('first',m.active);const old=m.active.position.clone();m.active.move(new Vector3(0,0,1),false,.1,new Vector3(1,0,0));assert.ok(m.active.position.z>old.z);assert.equal(m.active.facing.x,1);view.update(m,.016);assert.ok(camera.position.y>1.5&&camera.position.y<1.7);assert.equal(m.active.head.visible,false);assert.equal(m.active.torso.visible,false);view.setMode('broadcast',m.active);view.update(m,.016);assert.equal(m.active.head.visible,true);assert.equal(m.active.torso.visible,true);assert.equal(input.firstPerson,false);});
